version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into AWS ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 970547352475.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URL=970547352475.dkr.ecr.us-east-1.amazonaws.com/level_5/labs
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo running building stage...
      - docker build -t $REPO_URL:latest .
      - docker tag $REPO_URL:latest $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing the docker image
      - docker push $REPO_URL:latest
      - docker push $REPO_URL:$IMAGE_TAG
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPO_URL:$IMAGE_TAG > imagedefinitions.json 
      - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json

